# Generated by Django 2.1 on 2021-12-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='district',
            field=models.CharField(default='3', max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image1',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='post_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='post_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='post_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='image4',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='post_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='mobile',
            field=models.CharField(default=2222222, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='pincode',
            field=models.CharField(default=33333333, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.CharField(default=333333333, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.CharField(default=33333333, max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=2200),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
