# Generated by Django 2.1 on 2021-12-22 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211221_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='catagory',
            field=models.CharField(default=django.utils.timezone.now, max_length=22),
            preserve_default=False,
        ),
    ]
