# Generated by Django 2.1 on 2021-12-27 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20211227_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='catagory',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=3200),
        ),
        migrations.AlterField(
            model_name='post',
            name='mobile',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='pincode',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(1)]),
        ),
    ]
